---
title: Comparing Least Squares Calculations
abstract: |
  Many statistics methods require one or more least squares problems to
  be solved. There are several ways to perform this calculation, using
  objects from the base R system and using objects in the classes
  defined in the `Matrix` package.

  We compare the speed of some of these methods on a very small example
  and on a example for which the model matrix is large and sparse.
author: |
  Douglas Bates\
  R Development Core Team\
  [Douglas.Bates@R-project.org](Douglas.Bates@R-project.org){.uri}
date: '2024-06-01'
packages:
  cran: []
  bioc: []
vignette: |-
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{Comparisons of Least Squares calculation speeds}
output: rmarkdown::html_vignette

---

::: article
To remove warning messages, setup code chunk use knitr option
`warning=FALSE`.

``` {r setup,include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```

When the option OutDec is not `.`, put numbers in `\text`. See #348.

``` r
try this:
`r 1+1`
```

``` {r }
options(OutDec = ',')
```

This is the first test. abc `r 0.6` def

another test $a = `r 0.6`$.

and the last one $a = `r '0.6'`$.

``` {r }
options(OutDec = '.')
```

This is the first test. abc `r 0.6` def

another test $a = `r 0.6`$.

and the last one $a = `r '0.6'`$.

``` {r test}
# Define the cars vector with 5 values
cars <- c(1, 3, 6, 4, 9)
plot(cars, type="o", col="blue")
title(main="Autos", col.main="red", font.main=4)
```

Let's test another image from R code chunk:

``` {r image}
library(Matrix)
data(CAex, package = "Matrix")
print(image(CAex, main = "image(CAex)")) # print(.) needed for Sweave
```
:::
