\documentclass{article}
\usepackage{amsmath}
\begin{document}

\title{Comparing Least Squares Calculations}
\author{Douglas Bates\\R Development Core Team\\\email{Douglas.Bates@R-project.org}}
\abstract{
  Many statistics methods require one or more least squares problems
  to be solved.  There are several ways to perform this calculation,
  using objects from the base R system and using objects in the
  classes defined in the \code{Matrix} package.

  We compare the speed of some of these methods on a very small
  example and on a example for which the model matrix is large and
  sparse.
}

When the option OutDec is not \texttt{.}, put numbers in \texttt{\textbackslash{}text}. See \#348.

\begin{verbatim}
try this:
\Sexpr{1+1}
\end{verbatim}

<<>>=
options(OutDec = ',')
@

This is the first test. abc \Sexpr{0.6} def

another test $a = \Sexpr{0.6}$.

and the last one $a = \Sexpr{'0.6'}$.

<<>>=
options(OutDec = '.')
@

This is the first test. abc \Sexpr{0.6} def

another test $a = \Sexpr{0.6}$.

and the last one $a = \Sexpr{'0.6'}$.

<<test>>=
# Define the cars vector with 5 values
cars <- c(1, 3, 6, 4, 9)
plot(cars, type="o", col="blue")
title(main="Autos", col.main="red", font.main=4)
@

\end{document}